# Generated by Django 4.2 on 2026-03-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("market_cap", models.BigIntegerField()),
                ("volume_24h", models.BigIntegerField()),
                ("circulating_supply", models.BigIntegerField()),
                ("total_supply", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
