# Generated by Django 4.2 on 2026-03-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Token",
        ),
    ]
